server:
  port: 8080
  
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${host}:${port}/${database}?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false&AllowPublicKeyRetrieval=True&serverTimezone=UTC
    username: ${username}
    password: ${password}