server:
  port: 8080
  
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/api_db?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false&AllowPublicKeyRetrieval=True&serverTimezone=UTC
    username: root
    password: 123456